name : Deploy to Cloud Run

on:
  push:
    branch:
      main

env:
  PROJECT_ID : ${{ secrets.GCP_PROJECT_ID}}
  SERVICE_NAME: ksetrikah-service
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permission:
      contents: 'read'
      packages: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        usues: google-github-actions/auth@v2
        with: 
          credentials_json: ${{ secrets.GCP_SA_KEY}}

      - name: Set up Cloud SDK
        uses: google-github0-actions/setup-gcloud@v2

      - name: Build and Push Container
        run: |
            docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
            docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--port=5000 --allow-unauthenticated --memory=2Gi'
          env_vars: |
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
            ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}
            FRONTEND_URL=https://${{ env.SERVICE_NAME }}-${{ env.PROJECT_ID }}.a.run.app

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
    

        
